### ISSUE TITLE
Unable to create LDAP account

### ISSUE THREAD

**Issue by egeste** [hlavki/g-suite-identity-sync#15]
## After much effort I was able to get the service running & log in:
![screenshot from 2018-09-04 10-58-59](https://user-images.githubusercontent.com/536059/45048846-c7657000-b031-11e8-881c-724f739cc2cd.png)

## But when I attempt to save my account to LDAP I see the following error:
![screenshot from 2018-09-04 10-52-33](https://user-images.githubusercontent.com/536059/45048705-73f32200-b031-11e8-990c-be0c54ca78d4.png)

Any ideas on what might be happning here?

**Comment by hlavki** [comment]
@egeste, same with previous issue, could you please paste exception from log? thanks

**Comment by hlavki** [comment]
Also do you use version 0.3.3?

**Comment by egeste** [comment]
@hlavki I'm using the docker image from dockerhub, specifically the image identifier I'm using is `hlavki/g-suite-identity-sync:latest`, which looks like it's a reference to `0.3.3`. I'll post the logs a little later today. Thanks for this project and for helping out. I'll make sure I include logs with any future requests or problems.

Cheers.

**Comment by hlavki** [comment]
No problem, it's ok to not post logs here, because can contain confidential information. It's better to send log files directly to my email.

**Comment by egeste** [comment]
It looks like the actual error has something to do with this line:

`�[90m17:38:57.457�[0m �[1;33mWARN �[m �[90m[qtp1966079899-116]�[0m Group for external accounts null does not exists
`

**Comment by egeste** [comment]
Followup: I flipped the "sync password" toggle on and now it works. It's not optional.

**Comment by hlavki** [comment]
No, sync password toggle is optional. I've tested it righ now. I think your problem was in expired session, which was reason of that 401 error. Anyway, glad to hear it works!

**Comment by egeste** [comment]
Expired session? Is there something I need to do to clear an old session or something? I authenticated just before I attempted

**Comment by hlavki** [comment]
No, nothing like that, but user's session expires after some time of inactivity. Obviously not your scenario. Strange.
