### ISSUE TITLE
Don't try to fuck with me!

### ISSUE THREAD

**Issue by egeste** [hlavki/g-suite-identity-sync#16]
https://github.com/hlavki/g-suite-identity-sync/blob/ead9ae4d48388c9e3c2b360a8420b3976244e59a/services-rest/src/main/java/eu/hlavki/identity/services/rest/model/CreateAccountData.java#L13

https://github.com/hlavki/g-suite-identity-sync/blob/ead9ae4d48388c9e3c2b360a8420b3976244e59a/services-rest/src/main/java/eu/hlavki/identity/services/rest/model/UpdateAccountData.java#L11

**Comment by hlavki** [comment]
:) sorry, will change that, anyway this error should appear only when you somehow break javascript checks and send invalid password to backend.

**Comment by hlavki** [comment]
Argh, I can reproduce it. You should not be able to create/update account when passwords are invalid. Thanks for report.

**Comment by egeste** [comment]
Well my thought was that I can't put this in front of my CEO and have him sync his creds into LDAP with this tool because as soon as he sees that message he's going to freak out and be like "did someone just steal my password?" :/

**Comment by hlavki** [comment]
new version 0.3.4 released
