### ISSUE TITLE
Sign In Page Loop

### ISSUE THREAD

**Issue by BabuHzera** [hlavki/g-suite-identity-sync#18]
Hello, i'm trying to sync my g suite to an new ldap server, it's an vm with ubuntu 16.04. The ldap looks to be working fine, in the phpldapadmin i notice that the api created two OU's(Groups/People).

I got some google api problems with the localhost:8181, i normally access the server via local IP address (192.168.1.xxx), to work around this i've changed the hosts file to respond on foo-server.com and then on the URL Redirect i used the foo-server.com:8181.

When i access the foo-server.com:8181 it shows the sign in page and button, using my gsuite credentials it asks for the 2 Factor Auth in my mobile, looks like the authentication is ok, but it goes back to the sign in page and stays on this loop. 

Kind of stuck there, could u help me ?

Follows the full log file;
[logs.log](https://github.com/hlavki/g-suite-identity-sync/files/2420629/logs.log)

Best Regards

**Comment by hlavki** [comment]
@BabuHzera, it looks like you did not finish installation steps from [Wiki](https://github.com/hlavki/g-suite-identity-sync/wiki/Install).

**Comment by BabuHzera** [comment]
Hey @hlavki, i did all the steps, following then step by step. first on g suite, then on my vm. 

Could u give me ur e-mail so i can send u more details about the install ?

Thanks in advance

**Comment by hlavki** [comment]
My email should be visible in my profile.

**Comment by hlavki** [comment]
@BabuHzera does that means, it works for you?
