### ISSUE TITLE
Hardcoded Public Client URL

### ISSUE THREAD

**Issue by bclermont** [hlavki/g-suite-identity-sync#3]
It seem that the client URL hardcode https://localhost:8443: https://github.com/hlavki/g-suite-identity-sync/blob/ab347c294d61bbe2dc355ca8bd0df88037aba333/services-rest/src/main/config/eu.hlavki.identity.properties#L1

this is problematic in many ways:

first, that port is not exposed https://github.com/hlavki/g-suite-identity-sync/blob/master/distribution/src/main/docker/Dockerfile#L29

then, how can my users access the web server of my deployment and authenticate?

https://localhost:8443 is a valid URL but only on the docker host. not where users are.

I want to use https://hub.docker.com/_/traefik/ to terminate https and forward traffic to the container.
So, `hlavki/g-suite-identity-sync` can either get it's hostname from the HTTP headers or from a configuration

**Comment by hlavki** [comment]
Thanks @bclermont for info. I'll look to traefik and try it.

**Comment by hlavki** [comment]
I fixed it and removed `hostname` configuration property and added [compose example](https://github.com/hlavki/g-suite-identity-sync/blob/master/docker-compose-traefik.yml) with traefik. 

Important note is that you have to use latest snapshot version of image `hlavki/g-suite-identity-sync:0.3.0-SNAPSHOT` and change configuration name to `eu.hlavki.identity.google`:

```
config:edit eu.hlavki.identity.google
config:property-set oauth2.serviceAccount.privateKey.passphrase notasecret
config:property-set oauth2.serviceAccount.privateKey.file /opt/karaf/etc/keystore/service-account.p12
config:update
```

The new version will be released soon.
