### ISSUE TITLE
"No service was found." when clicking Sign In

### ISSUE THREAD

**Issue by faun88** [hlavki/g-suite-identity-sync#33]
Hi,

We currently have a FreeRADIUS running, but would like to login with our Gsuite credentials. 

After running a few times through all commands in the installation procedure, I'm hitting the same error "No service was found." when clicking Sign in on http://localhost:8181/#/sign-in  - Screenshot [here](https://monosnap.com/file/vEaHQTpbcruxDHREdOI9sUoHMRUcdu).

Some files that might help:

[karaf.log
](https://www.dropbox.com/s/ld1ocbnvpiwhnrl/karaf.log?dl=0)

[(anonymized) docker-compose.yml](https://www.dropbox.com/s/wd4r3ih3sqxjv1f/docker-compose.yml?dl=0)

Personally I think there is something wrong with my docker-compose file, as I'm not really sure of the variables. Could you perhaps enlighten me which we could choose ourselves and which should match what variable in our Gsuite admin? 

Note we're not using LDAP already, I wasn't sure if one is created with the Docker or we should create one ourselves first ?

Many thanks!

PS: A video tutorial for the Gsuite configuration would be really helpful!

**Comment by hlavki** [comment]
`SLAPD_PASSWORD` and  `LDAP_ADMIN_PASSWORD` must be same in `docker-compose.yml`

**Comment by hlavki** [comment]
And btw I am working on simpler configuration and then I'll prepare video tutorial

**Comment by faun88** [comment]
Hi, `SLAPD_PASSWORD` and `LDAP_ADMIN_PASSWORD `are indeed the same but the docker is still not working (same issue).

Is it correct that all LDAPD_ variables can be chosen freely and all GSUITE_ variables should match our Gsuite setup?

**Comment by hlavki** [comment]
try to clean all and setup from scratch:
```
docker-compose down -v
docker-compose up -d
```

> Is it correct that all LDAPD_ variables can be chosen freely and all GSUITE_ variables should match our Gsuite setup?

Yes, that's generaly true

**Comment by faun88** [comment]
It's still not working - something is wrong with my Gsuite settings I suppose:

Last output  from `docker-compose logs -f `:

`identity_1  | 21:22:21.865 INFO  [CM Configuration Updater (ManagedService Update: pid=[org.apache.cxf.osgi])] Service account private key was not  loaded from null`

[Full output](https://www.dropbox.com/s/5h8wshhtivs9xc4/log.txt?dl=0)

**Comment by faun88** [comment]
Hey,

After double-checking our Gsuite settings a few times, I don't think the issue is with my Gsuite settings now as the private key is successfully loaded but there appears to be an issue by reaching http://localhost:8181/cxf/oidc/

[Full docker logs](https://www.dropbox.com/s/abizcm2moumjxt3/dockerlogs.txt?dl=0)

[Karaf.log](https://www.dropbox.com/s/ld1ocbnvpiwhnrl/karaf.log?dl=0)

```
identity_1  | 09:23:48.352 INFO  [sshd-SshServer[7a28fc83]-nio2-thread-2] Session karaf@/127.0.0.1:53836 authenticated
identity_1  | 09:23:48.854 INFO  [CM Configuration Updater (Update: pid=eu.hlavki.identity.google)] Google Configuration changed
identity_1  | 09:23:48.856 INFO  [CM Configuration Updater (Update: pid=eu.hlavki.identity.google)] Configuring GSuiteDirectoryService ...
identity_1  | 09:23:48.856 INFO  [CM Configuration Updater (Update: pid=eu.hlavki.identity.google)] Token lifetime set to 3600
identity_1  | 09:23:49.012 INFO  [CM Configuration Updater (Update: pid=eu.hlavki.identity.google)] Service account private key  loaded from /opt/karaf/etc/identity/service-account.p12
identity_1  | 09:23:51.921 WARN  [qtp1203710790-124] Can't find the request for http://localhost:8181/cxf/identity/user's Observer
identity_1  | 09:23:53.492 WARN  [qtp1203710790-171] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:25:48.104 WARN  [qtp1203710790-127] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:25:50.944 WARN  [qtp1203710790-124] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:25:54.724 WARN  [qtp1203710790-127] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:25:59.893 WARN  [qtp1203710790-124] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:26:02.657 WARN  [qtp1203710790-127] Can't find the request for http://localhost:8181/cxf/oidc/'s Observer
identity_1  | 09:26:20.503 WARN  [qtp1203710790-165] Can't find the request for http://localhost:8181/cxf/identity/user's Observer
identity_1  | 09:26:21.930 WARN  [qtp1203710790-124] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:26:28.718 WARN  [qtp1203710790-167] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:26:30.770 WARN  [qtp1203710790-124] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
identity_1  | 09:26:34.871 WARN  [qtp1203710790-171] Can't find the request for http://localhost:8181/cxf/oidc/rp's Observer
```
