### ISSUE TITLE
Error after installatioon

### ISSUE THREAD

**Issue by netifysrl** [hlavki/g-suite-identity-sync#43]
Hi After installatoon i receive this error, i'm new in docker, can you help me please ?
  
Unable to start container for blueprint bundle eu.hlavki.identity.gsync-services-synchronize-api/0.4.3 due to unresolved dependencies [(objectClass=eu.hlavki.identity.services.ldap.LdapAccountService)]
identity_1  | java.util.concurrent.TimeoutException
identity_1  |   at org.apache.aries.blueprint.container.BlueprintContainerImpl$1.run(BlueprintContainerImpl.java:393)
identity_1  |   at org.apache.aries.blueprint.utils.threading.impl.DiscardableRunnable.run(DiscardableRunnable.java:45)
identity_1  |   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
identity_1  |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
identity_1  |   at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
identity_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
identity_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
identity_1  |   at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hlavki** [comment]
@netifysrl, can you send me your docker-compose.yml ? You can use email in my profile.

**Comment by hlavki** [comment]
Original problem fixed via email. Please open open new issue, if there is another problem.

**Comment by boomzero** [comment]
Hi @hlavki , may I know how did you fix the problem?
I'm facing the same one (latest version).
Thank you very much !

**Comment by hlavki** [comment]
Hi @boomzero, there was an invalid username format for LDAP. Value for `SLAPD_BIND_DN` should be `cn=admin,dc=domain,dc=com`. But it's possible that this is not your case. You can send me your anonymized docker-compose.yml if you want.
