### ISSUE TITLE
work on the real domain

### ISSUE THREAD

**Issue by sysadmin-ut** [hlavki/g-suite-identity-sync#49]
I'm trying to use a Docker container. On localhost authorization works. But for authorization in google requires https. I made proxy https through nginx. But at authorization request I receive an error:

`The redirect URI in the request, http://my.domain.com:8181/cxf/oidc/rp/complete, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs:`

What options do you have on a real domain? Thank you in advance for your answer.

**Comment by hlavki** [comment]
Hi @sysadmin-ut,
I think you need to add your domain to Authorized callback URI in web app credentials like this screenshot. Link to console: https://console.cloud.google.com/apis/credentials

![image](https://user-images.githubusercontent.com/5858133/66396222-93e5d980-e9d9-11e9-85af-b3d3d23ba5e0.png)

let mi know if it helps, thanks

**Comment by sysadmin-ut** [comment]
Thanks for the answer. It is added to Google(https://my.domain.com/cxf/oidc/rp/complete). But the answer comes with the port 8181 and proto http.  Perhaps the problem is in the proxying itself. Is it possible to install ssl inside the container? Or is it not required?

**Comment by hlavki** [comment]
It is possible to install certificate, but you don't need it. Yesterday I did example using traefik v2 and let's encrypt. I will add it to source code today or tomorrow and will let you know.

**Comment by hlavki** [comment]
@sysadmin-ut, I've added example [docker-compose-traefik-v2-ssl.yml](https://github.com/hlavki/g-suite-identity-sync/blob/master/docker-compose-traefik-v2-ssl.yml) using traefik v2 and Let's encrypt SSL certificate.

I also have some installation using apache2, but none of them with nginx. But if traefik and apache2 works, nginx should also.

**Comment by sysadmin-ut** [comment]
Thanks. It works.
