### ISSUE TITLE
 GSSAPI Error: Unspecified GSS failure

### ISSUE THREAD

**Issue by renanwilliam** [hlavki/g-suite-identity-sync#50]
Hi,

I have installed with success and all web interface features is working. But after add my user, when I try to bind LDAP service I'm receiving:
`SASL [conn=1003] Failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Key table file '/etc/krb5.keytab' not found)`

Attached log files:
[log_file.txt](https://github.com/hlavki/g-suite-identity-sync/files/3740466/log_file.txt)

**Comment by hlavki** [comment]
This seems to be out of scope of this project, but what is your LDAP server configuration? Did you use example compose file?

**Comment by renanwilliam** [comment]
Yes, I've used the example compose file. After some reboots, it's starting to works. It's ok now.
