### ISSUE TITLE
"No service was found" when clicking on Sign In

### ISSUE THREAD

**Issue by vvapp** [hlavki/g-suite-identity-sync#51]
Hi,

I am trying to use your project and I have followed the installation instructions on Ubuntu 19.04 instance. I can bring up the sign in page, but when I try to click on Sign In, I get "No service was found". I am using docker-compose.yaml from your project.

Error in logs:
identity_1  | 20:04:00.820 WARN  [qtp2009298267-108] Can't find the request for http://35.236.57.123:8181/cxf/oidc/
rp's Observer

Start up logs:
ldap_1      | *** Set environment for startup files
ldap_1      | *** Environment files will be proccessed in this order : 
ldap_1      | Caution: previously defined variables will not be overriden.
ldap_1      | /container/environment/99-default/default.yaml
ldap_1      | /container/environment/99-default/default.startup.yaml
ldap_1      | 
ldap_1      | To see how this files are processed and environment variables values,
ldap_1      | run this container with '--loglevel debug'
ldap_1      | *** Running /container/run/startup/:ssl-tools...
ldap_1      | *** Running /container/run/startup/slapd...
ldap_1      | Start OpenLDAP...
ldap_1      | Waiting for OpenLDAP to start...
ldap_1      | Add TLS config...
ldap_1      | Disable replication config...
ldap_1      | *** /container/run/startup/slapd failed with status 49
ldap_1      | 
ldap_1      | *** Killing all processes...
gsuiteidentitysync_ldap_1 exited with code 1

Can you please help resolve this issue?

Thanks,
Vasavi

**Comment by hlavki** [comment]
hi @vvapp, sorry, can't help you with this info. Can you send me your `docker-compose.yml` and full log message? You can find my email in github profile.

**Comment by hlavki** [comment]
hi @vvapp, according to logs it looks like LDAP service is not running.

**Comment by hlavki** [comment]
Closing due inactivity. Feel free to reopen is problem occurs.
