### ISSUE TITLE
Central Repo no longer accepts HTTP

### ISSUE THREAD

**Issue by bartusek27** [hlavki/g-suite-identity-sync#57]
Effective January 15, 2020, The Central Repository no longer supports insecure communication over plain HTTP and requires that all requests to the repository are encrypted over HTTPS.

More info for e.g.:
https://stackoverflow.com/questions/59763531/maven-dependencies-are-failing-with-501-error-in-jenkins

Because of this, when I am trying to use docker image, it fails on getting files from central.

**Comment by hlavki** [comment]
thanks for info @bartusek27, this upstream problem [KARAF-6600](http://issues.apache.org/jira/browse/KARAF-6600) will be fixed in upcoming release 4.2.8. I'll release new version right after this.

**Comment by hlavki** [comment]
Thanks to this issue I discovered bug, because application should not download any artifact on startup. Thanks for report

**Comment by bartusek27** [comment]
Thank you for your response!
