### ISSUE TITLE
Question: Is it possible to sync all GSuite users into the LDAP without manually sign-in for each user?

### ISSUE THREAD

**Issue by lesmono** [hlavki/g-suite-identity-sync#60]
Hi @hlavki, what a great app.
I am curious in some of the functionality of this application. Is it possible to do **full periodical sync** of the **G-Suite** account and group into the LDAP without forcing the user to manually sign-in one by one?

**Comment by hlavki** [comment]
Thanks @lesmono, this functionality is not supported at this moment. The reason is simple:
1. There is no way, how to synchronize password from GSuite to LDAP

So if you synchronize all users without setting password, they can't login.

**Comment by lesmono** [comment]
Ok noted. When does `scheduled synchronizers` run? Can we set the value (e.g every 1 minute, or every 01:00 AM )?
Also, what version of JDK to develop this app? I tried to build and run it in my local, but produce some errors, I think it's related to the version of installed JDK.

Here is the error:
```
../services/google/api/src/main/java/eu/hlavki/identity/services/google/impl/PushNotificationServiceImpl.java:[98,24] cannot find symbol
[ERROR]   symbol:   method isEmpty()
[ERROR]   location: variable channel of type java.util.Optional<eu.hlavki.identity.services.google.model.PushChannel>
```

```
~ java -version

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by hlavki** [comment]
1. To build application you need **java 11**.
1. You can configure when scheduler runs. Default is every hour, but you can configure it. It uses apache karaf scheduler. The way how to configure you can find in [karaf documentation](http://karaf.apache.org/manual/latest/#_scheduler).
1. If you need run synchronization every minute, then better option is to use [push notifications](https://github.com/hlavki/g-suite-identity-sync/wiki/Push-Notifications), where google notifies you on every change.

**Comment by hlavki** [comment]
Closing this, but feel free to reopen or create new one If you have another question.

**Comment by lesmono** [comment]
Thanks, man, appreciated. I hope I can contribute more to this cool app in the future.
