### ISSUE TITLE
Question: Can we run on clustered mode, or only support standalone mode?

### ISSUE THREAD

**Issue by lesmono** [hlavki/g-suite-identity-sync#61]
Hi, @hlavki I will try to run this on AWS ECS, is this app support clustered mode, or only run in standalone mode?

**Comment by hlavki** [comment]
Hi @lesmono, sorry for later answer. Since this project was designed for smaller companies, there is no support for clustered deployment. Anyway if you take what this application do, I think also standalone mode is able to handle large companies without problem.

**Comment by lesmono** [comment]
Aha, that makes sense. On the set-up for the first time, we input some `json` data from the service account created before, is it stored persistently? Can we move all configuration to `ENVIRONMENT VARIABLES`?

**Comment by hlavki** [comment]
@lesmono, you can use environment variables for subset of configuration at this moment. Not for all. Feel free to open issue or create pull request.
