### ISSUE TITLE
problem when I log in 

### ISSUE THREAD

**Issue by AhmadAbuHashem** [hlavki/g-suite-identity-sync#62]
I hope you can guide me through in my problem.
I have g-suite-identity-sync in docker.  But When I go to it through IP adress I get 
![g-suit-1](https://user-images.githubusercontent.com/37737394/78134444-7477b880-7420-11ea-8d63-1f9383cc3317.png)

instead of the picture you have showed.
I am not so technically involved in docker but I would like to have this solution. how can I get the right solution.

**Comment by hlavki** [comment]
It seem that you have older version, which configuration is not compatible with latest version. There is also wiki about [upgrade from older version](https://github.com/hlavki/g-suite-identity-sync/wiki/Upgrade-from-0.3.x)

**Comment by hlavki** [comment]
According to gitter discussion, now it works
