### ISSUE TITLE
I have moved the whole application to a new server. I have a problem starting  osixia/openldap 

### ISSUE THREAD

**Issue by Ahmadhashem86** [hlavki/g-suite-identity-sync#66]
# docker ps -a 
7c81150f96a2        osixia/openldap                "/container/tool/run"    8 minutes ago       Exited (1) 3 seconds ago                                                                    g-suite-identity-sync_ldap_1

I can send the log file and docker-compose file 
version: "3"
services:
  identity:
    image: hlavki/g-suite-identity-sync
    ports:
      - 8181:8181
      - 8101:8101
    environment:
      - SLAPD_BIND_DN=cn=admin,dc=netset,dc=com
      - SLAPD_BASE_DN=dc=netset,dc=com
      - SLAPD_PASSWORD=Xqjq51
      - GSUITE_DOMAIN=netset.com
      - GSUITE_SERVICE_ACCOUNT_EMAIL=gsuite-ldap-svc@gsuite-ldap-217708.iam.gserviceaccount.com 
      - GSUITE_SERVICE_ACCOUNT_SUBJECT=ahmashem@netset.com
      - GSUITE_CLIENT_ID=556744189533-3cqad9qmlk40qm7av2b2n.apps.googleusercontent.com 
      - GSUITE_CLIENT_SECRET=KENb0yTQDKt-ZoE2x
    depends_on:
      - ldap
    volumes:
      - identity-config:/opt/karaf/etc/identity
  ldap:
    image: osixia/openldap
    hostname: ldap.netset.se
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_LOG_LEVEL: "trace"
      LDAP_ORGANISATION: "Netset"
      LDAP_DOMAIN: "netset.com"
      LDAP_ADMIN_PASSWORD: "XqjqoBH51"
      LDAP_CONFIG_PASSWORD: "XqH51"
      LDAP_TLS_CRT_FILENAME: "cert.pem"
      LDAP_TLS_KEY_FILENAME: "privkey.pem"
      LDAP_TLS_CA_CRT_FILENAME: "chain.pem"
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
    - ./ldap-data:/var/lib/ldap
    - ./ldap-config:/etc/ldap/slapd.d
    - ./certs:/container/service/slapd/assets/certs

volumes:
  identity-config:   
  ldap-config:
  ldap-data:
  certs:

**Comment by hlavki** [comment]
Sorry, this is out of scope of this project
