### ISSUE TITLE
Problem : got "Cannot authenticate user. Status: 403"

### ISSUE THREAD

**Issue by theobaud-faber** [hlavki/g-suite-identity-sync#67]
Hello,

I try for couple of days to understand why I have this error.
I know that's the message speaks for itself. But I don't get it why, because I have a identity.admins group created, I'm a member of this group and my account has admin permissions.

When I "sign in" with mypage:8181/#/sign-in, I've got this with the web console :

```
Access denied - only for authenticated users:                     auth.js:73:16
Appropriate route, user/guest has rights to visit:                /auth-wait auth.js:79:16
Cannot authenticate user. Status: 403                             auth.js:29:22
ERRdata: [object Object]                                          auth.js:30:22
Appropriate route, user/guest has rights to visit:               /sign-in auth.js:79:16
```

Can you help me please ?

​

​

**Comment by hlavki** [comment]
hi @TheoB-faber, can you please provide full log from docker container? You can send it to my email. thanks

**Comment by hlavki** [comment]
Closing due inactivity
