### ISSUE TITLE
Client is unauthorized to retrieve access tokens using this method

### ISSUE THREAD

**Issue by cdejardin** [hlavki/g-suite-identity-sync#7]
Hello, 

I did follow all the steps in the documentation, i launch the containers, i open my browser to the right URL, i clic on sign-in, i'm logged with the right google account, and when i'm redirected, i got this error on the logs:

`identity_1  | 2018-05-14T10:01:41,515 | INFO  | qtp1837767860-96 | LoggingOutInterceptor            | 41 - org.apache.cxf.cxf-core - 3.2.2 | Outbound Message
identity_1  | ---------------------------
identity_1  | ID: 28
identity_1  | Response-Code: 401
identity_1  | Content-Type: application/json;charset=utf-8
identity_1  | Headers: {Accept-Ranges=[none], Alt-Svc=[hq=":443"; ma=2592000; quic=51303433; quic=51303432; quic=51303431; quic=51303339; quic=51303335,quic=":443"; ma=2592000; v="43,42,41,39,35"], Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], content-type=[application/json;charset=utf-8], Date=[Mon, 14 May 2018 10:01:41 GMT], Expires=[Mon, 01 Jan 1990 00:00:00 GMT], Pragma=[no-cache], Server=[ESF], transfer-encoding=[chunked], Vary=[Accept-Encoding], X-Content-Type-Options=[nosniff], X-Frame-Options=[SAMEORIGIN], X-XSS-Protection=[1; mode=block], Content-Type=[application/json; charset=utf-8]}
identity_1  | Payload: {
identity_1  |   "error" : "unauthorized_client",
identity_1  |   "error_description" : "Client is unauthorized to retrieve access tokens using this method."
identity_1  | }
identity_1  | --------------------------------------
`

**Comment by hlavki** [comment]
Hi,

I think there is some problem with [Delegating domain-wide authority to the service account](https://github.com/hlavki/g-suite-identity-sync/wiki/GSuite-configuration#craete-service-account-and-permissions).

According to [documentation](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) you have to specify **Client ID** and scopes in comma delimited format: 
```
https://www.googleapis.com/auth/admin.directory.group.readonly, https://www.googleapis.com/auth/admin.directory.user
```

**Comment by cdejardin** [comment]
Hi,

Thanks a lot for the quick answer, i originally did not understand that we had to put the 2 scopes.

It's working as expected now, i'm connected.

I'll close the issue.

Best regards.

**Comment by maximka777** [comment]
Hey @hlavki 👋 
I faced with such issue as well. I set necessary permissions to service account, but still get 401.
<img width="522" alt="Снимок экрана 2019-05-17 в 17 57 44" src="https://user-images.githubusercontent.com/15107753/57936811-4c956a00-78cd-11e9-97cf-4d2566f9e24d.png">
