### ISSUE TITLE
sonatype nexus

### ISSUE THREAD

**Issue by hdang-omnirobotic** [hlavki/g-suite-identity-sync#85]
Hi
I would like to use this tool to interface it between sonatype nexus and google as it seem possible but i did not understand how.

Can you help me ?

Thanks

**Comment by hlavki** [comment]
Hi, this software synchronizes G Suite (now Google Workspace) users and groups to LDAP. Then you can use this LDAP as an authentication and authorization provider for your Sonatype Nexus. Keep in mind that it's impossible to synchronize passwords from Google Workspace, so you have to create one in LDAP.
