### ISSUE TITLE
Samba setup issue

### ISSUE THREAD

**Issue by pjt0620** [hlavki/g-suite-identity-sync#92]
Hi, great work so far on this project.
I'm having an issue when running the command
`docker-compose exec identity /opt/karaf/bin/client     'config:edit eu.hlavki.identity.ldap; config:property-set ldap.users.dnAttr cn; config:property-set ldap.users.baseDN CN=Users; config:update'`
I get a prompt that says "Enter user:" what user is this referring to?

**Comment by hlavki** [comment]
fixed by 873c7ad8f9fa353f79dcb1a603c11502afb5e20b released in v0.6.1
